### ISSUE TITLE
Create docker-compose.yml

### ISSUE THREAD

**Issue by sametaln** [bounswe/bounswe2024group7#43]
Docker compose will allow us to link and manage our frontend and backend containers easily. Also the database linking is going to be useful. Currently, there is only frontend service that will be running with our `docker-compose.yml` file. We can improve this further.

```yaml
version: '3.8'

services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
```

**Comment by sametaln** [comment]
```
version: '3.8'

services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  backend:
    build: ./artifact_backend
    volumes:
      - ./artifact_backend:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE 1
    env_file:
      - .env
    depends_on:
      - db
    restart: on-failure

  db:
    image: mysql:latest
    container_name: artifact_mysql
    restart: always
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "${MYSQL_USER}", "-p ${MYSQL_ROOT_PASSWORD}", "-e", "SELECT 1"]
      timeout: 20s
      retries: 10

volumes:
  data:
  ```
  
  Here is our latest docker-compose.yml file.
